// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANPla3lBm4KUOHOv6MMhcuuwyCCb2BngU',
    appId: '1:132852231325:web:0551c571716d0c05227874',
    messagingSenderId: '132852231325',
    projectId: 'autoalert-34b7f',
    authDomain: 'autoalert-34b7f.firebaseapp.com',
    storageBucket: 'autoalert-34b7f.firebasestorage.app',
    measurementId: 'G-P235E6K68H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDLPVV09A7-ZQJQzkounRVcO5NwfPuHCE',
    appId: '1:132852231325:android:8a104df49a281e85227874',
    messagingSenderId: '132852231325',
    projectId: 'autoalert-34b7f',
    storageBucket: 'autoalert-34b7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy89LtTBxMMvBl3vNaCYBro6fFZyrBzrU',
    appId: '1:132852231325:ios:0ad53cf64f0d1aaf227874',
    messagingSenderId: '132852231325',
    projectId: 'autoalert-34b7f',
    storageBucket: 'autoalert-34b7f.firebasestorage.app',
    iosBundleId: 'com.example.autoAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy89LtTBxMMvBl3vNaCYBro6fFZyrBzrU',
    appId: '1:132852231325:ios:0ad53cf64f0d1aaf227874',
    messagingSenderId: '132852231325',
    projectId: 'autoalert-34b7f',
    storageBucket: 'autoalert-34b7f.firebasestorage.app',
    iosBundleId: 'com.example.autoAlert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANPla3lBm4KUOHOv6MMhcuuwyCCb2BngU',
    appId: '1:132852231325:web:650baa655068e4ab227874',
    messagingSenderId: '132852231325',
    projectId: 'autoalert-34b7f',
    authDomain: 'autoalert-34b7f.firebaseapp.com',
    storageBucket: 'autoalert-34b7f.firebasestorage.app',
    measurementId: 'G-PT37X9G9CW',
  );

}