// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwQfzWtRDC6sZv7ucNPjZp_Q1M9bs4Zvc',
    appId: '1:886969377824:web:5a00a6009e5fea618f8845',
    messagingSenderId: '886969377824',
    projectId: 'alertauth-ed306',
    authDomain: 'alertauth-ed306.firebaseapp.com',
    storageBucket: 'alertauth-ed306.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2TQG4yWz6focoNx4nJEDXDTeBQU5S7xg',
    appId: '1:886969377824:android:583e052e969ad22b8f8845',
    messagingSenderId: '886969377824',
    projectId: 'alertauth-ed306',
    storageBucket: 'alertauth-ed306.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIMsTlTU0ROSNj8gLZh81in1MPx4wHJZk',
    appId: '1:886969377824:ios:06f9e5943b3197558f8845',
    messagingSenderId: '886969377824',
    projectId: 'alertauth-ed306',
    storageBucket: 'alertauth-ed306.firebasestorage.app',
    androidClientId: '886969377824-3t80j2i8sb1fn0uftk5hvsv4am5eire0.apps.googleusercontent.com',
    iosClientId: '886969377824-u3nlpkh5v13pir286p8o9mfp9ac1os2v.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIMsTlTU0ROSNj8gLZh81in1MPx4wHJZk',
    appId: '1:886969377824:ios:06f9e5943b3197558f8845',
    messagingSenderId: '886969377824',
    projectId: 'alertauth-ed306',
    storageBucket: 'alertauth-ed306.firebasestorage.app',
    androidClientId: '886969377824-3t80j2i8sb1fn0uftk5hvsv4am5eire0.apps.googleusercontent.com',
    iosClientId: '886969377824-u3nlpkh5v13pir286p8o9mfp9ac1os2v.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoAlert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwQfzWtRDC6sZv7ucNPjZp_Q1M9bs4Zvc',
    appId: '1:886969377824:web:3e24c8bb3cd50e1a8f8845',
    messagingSenderId: '886969377824',
    projectId: 'alertauth-ed306',
    authDomain: 'alertauth-ed306.firebaseapp.com',
    storageBucket: 'alertauth-ed306.firebasestorage.app',
  );

}